### ISSUE TITLE
Provide a gitops module to create CA Issuer in a cluster

### ISSUE THREAD

**Issue by seansund** [cloud-native-toolkit/terraform-gitops-ocp-ca-issuer#1]
Requirement for MAS Core release is manual instructions

**Comment by tcskill** [comment]
reference for ibm-cert manager to use custom issuer
https://www.ibm.com/docs/en/cpfs?topic=services-configuring-foundational-by-using-custom-resource#byoc

**Comment by tcskill** [comment]
closed with: https://github.com/cloud-native-toolkit/terraform-gitops-cp-maximo/pull/20
